require('dotenv').config();
const mongoose = require('mongoose');
const Product = require('../models/Product');

const products = [
  {
    nom: 'Maillot Sénégal Player 2026',
    slug: 'maillot-senegal',
    description: 'Maillot officiel du Sénégal par OBB STORE. Qualité premium, coupe ajustée, tissu respirant. Portez fièrement les couleurs nationales.',
    category: 'maillots',
    marque: 'OBB STORE',
    prix: 7000,
    ancienPrix: 10000,
    reduction: 30,
    stock: 45,
    tailles: ['S', 'M', 'L', 'XL'],
    couleurs: [{ nom: 'Rouge', code: '#E31E24' }, { nom: 'Jaune', code: '#FFD700' }],
    images: ['https://res.cloudinary.com/your-cloud-name/image/upload/v1/obb-store/maillot-senegal.jpg'],
    imagePrincipale: 'https://res.cloudinary.com/your-cloud-name/image/upload/v1/obb-store/maillot-senegal.jpg',
    gallery: ['https://res.cloudinary.com/your-cloud-name/image/upload/v1/obb-store/maillot-senegal.jpg'],
    variants: { label: 'Taille', options: ['S', 'M', 'L', 'XL'] },
    note: 4.5,
    nombreAvis: 124,
    vendu: 156,
    tags: ['football', 'sénégal', 'maillot'],
    featured: true,
    isPopular: true,
    isNewArrival: false,
    promoEndDate: new Date(Date.now() + 48 * 60 * 60 * 1000),
    isActive: true
  },
  {
    nom: 'T-shirt OBB Premium',
    slug: 'tshirt-obb-premium',
    description: 'T-shirt premium en coton bio. Coupe moderne, confort absolu. Le must-have de votre garde-robe.',
    category: 'tshirts',
    marque: 'OBB STORE',
    prix: 22000,
    stock: 78,
    tailles: ['S', 'M', 'L', 'XL'],
    couleurs: [{ nom: 'Noir', code: '#000000' }, { nom: 'Blanc', code: '#FFFFFF' }],
    images: ['https://res.cloudinary.com/your-cloud-name/image/upload/v1/obb-store/tshirt-obb.jpg'],
    imagePrincipale: 'https://res.cloudinary.com/your-cloud-name/image/upload/v1/obb-store/tshirt-obb.jpg',
    gallery: ['https://res.cloudinary.com/your-cloud-name/image/upload/v1/obb-store/tshirt-obb.jpg'],
    variants: { label: 'Taille', options: ['S', 'M', 'L', 'XL'] },
    note: 4.8,
    nombreAvis: 89,
    vendu: 234,
    tags: ['tshirt', 'premium', 'coton'],
    featured: true,
    isPopular: false,
    isNewArrival: true,
    isActive: true
  },
  {
    nom: 'Parfum Royal Oud',
    slug: 'parfum-royal-oud',
    description: 'Parfum luxueux aux notes de oud, ambre et santal. Longue tenue, sillage envoûtant. L\'essence de l\'élégance.',
    category: 'parfums',
    marque: 'OBB STORE',
    prix: 120000,
    ancienPrix: 150000,
    reduction: 20,
    stock: 23,
    couleurs: [{ nom: 'Or', code: '#D4AF37' }],
    images: ['https://res.cloudinary.com/your-cloud-name/image/upload/v1/obb-store/parfum-oud.jpg'],
    imagePrincipale: 'https://res.cloudinary.com/your-cloud-name/image/upload/v1/obb-store/parfum-oud.jpg',
    gallery: ['https://res.cloudinary.com/your-cloud-name/image/upload/v1/obb-store/parfum-oud.jpg'],
    variants: { label: 'Volume', options: ['50ml', '100ml', '200ml'] },
    note: 4.9,
    nombreAvis: 156,
    vendu: 89,
    tags: ['parfum', 'oud', 'luxe'],
    featured: true,
    isPopular: true,
    isNewArrival: false,
    isActive: true
  },
  {
    nom: 'Sneakers Urban White',
    slug: 'sneakers-urban-white',
    description: 'Sneakers urbaines minimalistes. Design épuré, confort optimal. Parfait pour un style casual chic.',
    category: 'chaussures',
    marque: 'OBB STORE',
    prix: 75000,
    stock: 34,
    tailles: ['40', '41', '42', '43', '44'],
    couleurs: [{ nom: 'Blanc', code: '#FFFFFF' }],
    images: ['https://res.cloudinary.com/your-cloud-name/image/upload/v1/obb-store/sneakers-white.jpg'],
    imagePrincipale: 'https://res.cloudinary.com/your-cloud-name/image/upload/v1/obb-store/sneakers-white.jpg',
    gallery: ['https://res.cloudinary.com/your-cloud-name/image/upload/v1/obb-store/sneakers-white.jpg'],
    variants: { label: 'Pointure', options: ['40', '41', '42', '43', '44'] },
    note: 4.6,
    nombreAvis: 67,
    vendu: 123,
    tags: ['sneakers', 'urbain', 'blanc'],
    featured: false,
    isPopular: false,
    isNewArrival: true,
    isActive: true
  },
  {
    nom: 'Maillot PSG Home 2024',
    slug: 'maillot-psg-home',
    description: 'Maillot domicile PSG 2024. Qualité officielle, design iconique. Pour les vrais supporters parisiens.',
    category: 'maillots',
    marque: 'PSG',
    prix: 25000,
    stock: 12,
    tailles: ['S', 'M', 'L', 'XL'],
    couleurs: [{ nom: 'Bleu Marine', code: '#00205B' }, { nom: 'Rouge', code: '#E31E24' }],
    images: ['https://res.cloudinary.com/your-cloud-name/image/upload/v1/obb-store/maillot-psg.jpg'],
    imagePrincipale: 'https://res.cloudinary.com/your-cloud-name/image/upload/v1/obb-store/maillot-psg.jpg',
    gallery: ['https://res.cloudinary.com/your-cloud-name/image/upload/v1/obb-store/maillot-psg.jpg'],
    variants: { label: 'Taille', options: ['S', 'M', 'L', 'XL'] },
    note: 4.7,
    nombreAvis: 203,
    vendu: 345,
    tags: ['football', 'psg', 'maillot'],
    featured: true,
    isPopular: false,
    isNewArrival: false,
    isActive: true
  },
  {
    nom: 'T-shirt Essential Black',
    slug: 'tshirt-essential-black',
    description: 'T-shirt essentiel noir. Basique mais indispensable. Coton premium, coupe ajustée.',
    category: 'tshirts',
    marque: 'OBB STORE',
    prix: 15000,
    stock: 2,
    tailles: ['S', 'M', 'L', 'XL'],
    couleurs: [{ nom: 'Noir', code: '#000000' }],
    images: ['https://res.cloudinary.com/your-cloud-name/image/upload/v1/obb-store/tshirt-black.jpg'],
    imagePrincipale: 'https://res.cloudinary.com/your-cloud-name/image/upload/v1/obb-store/tshirt-black.jpg',
    gallery: ['https://res.cloudinary.com/your-cloud-name/image/upload/v1/obb-store/tshirt-black.jpg'],
    variants: { label: 'Taille', options: ['S', 'M', 'L', 'XL'] },
    note: 4.3,
    nombreAvis: 45,
    vendu: 67,
    tags: ['tshirt', 'noir', 'essential'],
    featured: false,
    isPopular: false,
    isNewArrival: false,
    isActive: true
  },
  {
    nom: 'Maillot Real Madrid Home 2024',
    slug: 'maillot-real-madrid',
    description: 'Maillot domicile Real Madrid 2024. Qualité officielle, design emblématique. Pour les fans du club merengue.',
    category: 'maillots',
    marque: 'Real Madrid',
    prix: 28000,
    ancienPrix: 35000,
    reduction: 20,
    stock: 18,
    tailles: ['S', 'M', 'L', 'XL'],
    couleurs: [{ nom: 'Blanc', code: '#FFFFFF' }, { nom: 'Or', code: '#D4AF37' }],
    images: ['https://res.cloudinary.com/your-cloud-name/image/upload/v1/obb-store/maillot-real-madrid.jpg'],
    imagePrincipale: 'https://res.cloudinary.com/your-cloud-name/image/upload/v1/obb-store/maillot-real-madrid.jpg',
    gallery: ['https://res.cloudinary.com/your-cloud-name/image/upload/v1/obb-store/maillot-real-madrid.jpg'],
    variants: { label: 'Taille', options: ['S', 'M', 'L', 'XL'] },
    note: 4.8,
    nombreAvis: 312,
    vendu: 456,
    tags: ['football', 'real madrid', 'maillot'],
    featured: true,
    isPopular: true,
    isNewArrival: false,
    isActive: true
  },
  {
    nom: 'Parfum Ocean Breeze',
    slug: 'parfum-ocean-breeze',
    description: 'Parfum frais et aquatique aux notes marines. Idéal pour l\'été, légèreté et fraîcheur assurées.',
    category: 'parfums',
    marque: 'OBB STORE',
    prix: 45000,
    stock: 45,
    couleurs: [{ nom: 'Bleu', code: '#0077BE' }],
    images: ['https://res.cloudinary.com/your-cloud-name/image/upload/v1/obb-store/parfum-ocean.jpg'],
    imagePrincipale: 'https://res.cloudinary.com/your-cloud-name/image/upload/v1/obb-store/parfum-ocean.jpg',
    gallery: ['https://res.cloudinary.com/your-cloud-name/image/upload/v1/obb-store/parfum-ocean.jpg'],
    variants: { label: 'Volume', options: ['50ml', '100ml'] },
    note: 4.4,
    nombreAvis: 78,
    vendu: 134,
    tags: ['parfum', 'ocean', 'frais'],
    featured: false,
    isPopular: false,
    isNewArrival: true,
    isActive: true
  },
  {
    nom: 'Sneakers Sport Pro',
    slug: 'sneakers-sport-pro',
    description: 'Sneakers de performance pour le sport. Amorti maximal, respirantes, légères. Pour les athletes exigeants.',
    category: 'chaussures',
    marque: 'OBB STORE',
    prix: 55000,
    ancienPrix: 70000,
    reduction: 21,
    stock: 28,
    tailles: ['40', '41', '42', '43', '44', '45'],
    couleurs: [{ nom: 'Noir', code: '#000000' }, { nom: 'Rouge', code: '#E31E24' }],
    images: ['https://res.cloudinary.com/your-cloud-name/image/upload/v1/obb-store/sneakers-sport.jpg'],
    imagePrincipale: 'https://res.cloudinary.com/your-cloud-name/image/upload/v1/obb-store/sneakers-sport.jpg',
    gallery: ['https://res.cloudinary.com/your-cloud-name/image/upload/v1/obb-store/sneakers-sport.jpg'],
    variants: { label: 'Pointure', options: ['40', '41', '42', '43', '44', '45'] },
    note: 4.5,
    nombreAvis: 92,
    vendu: 167,
    tags: ['sneakers', 'sport', 'performance'],
    featured: true,
    isPopular: true,
    isNewArrival: false,
    isActive: true
  },
  {
    nom: 'T-shirt Oversize Street',
    slug: 'tshirt-oversize-street',
    description: 'T-shirt oversize style streetwear. Coupe large, coton lourd, design urbain. Tendance absolue.',
    category: 'tshirts',
    marque: 'OBB STORE',
    prix: 18000,
    stock: 56,
    tailles: ['S', 'M', 'L', 'XL', 'XXL'],
    couleurs: [{ nom: 'Gris', code: '#808080' }, { nom: 'Beige', code: '#F5F5DC' }],
    images: ['https://res.cloudinary.com/your-cloud-name/image/upload/v1/obb-store/tshirt-oversize.jpg'],
    imagePrincipale: 'https://res.cloudinary.com/your-cloud-name/image/upload/v1/obb-store/tshirt-oversize.jpg',
    gallery: ['https://res.cloudinary.com/your-cloud-name/image/upload/v1/obb-store/tshirt-oversize.jpg'],
    variants: { label: 'Taille', options: ['S', 'M', 'L', 'XL', 'XXL'] },
    note: 4.6,
    nombreAvis: 134,
    vendu: 289,
    tags: ['tshirt', 'oversize', 'streetwear'],
    featured: false,
    isPopular: true,
    isNewArrival: true,
    isActive: true
  },
  {
    nom: 'Maillot Bayern Munich Home',
    slug: 'maillot-bayern-munich',
    description: 'Maillot domicile Bayern Munich 2024. Qualité officielle, design classique bavarois. Pour les supporters du club.',
    category: 'maillots',
    marque: 'Bayern Munich',
    prix: 26000,
    stock: 15,
    tailles: ['S', 'M', 'L', 'XL'],
    couleurs: [{ nom: 'Rouge', code: '#DC052D' }, { nom: 'Blanc', code: '#FFFFFF' }],
    images: ['https://res.cloudinary.com/your-cloud-name/image/upload/v1/obb-store/maillot-bayern.jpg'],
    imagePrincipale: 'https://res.cloudinary.com/your-cloud-name/image/upload/v1/obb-store/maillot-bayern.jpg',
    gallery: ['https://res.cloudinary.com/your-cloud-name/image/upload/v1/obb-store/maillot-bayern.jpg'],
    variants: { label: 'Taille', options: ['S', 'M', 'L', 'XL'] },
    note: 4.7,
    nombreAvis: 178,
    vendu: 234,
    tags: ['football', 'bayern munich', 'maillot'],
    featured: true,
    isPopular: false,
    isNewArrival: false,
    isActive: true
  },
  {
    nom: 'Parfum Midnight Rose',
    slug: 'parfum-midnight-rose',
    description: 'Parfum floral et sensuel aux notes de rose et de patchouli. Élégance nocturne, sillage captivant.',
    category: 'parfums',
    marque: 'OBB STORE',
    prix: 85000,
    ancienPrix: 100000,
    reduction: 15,
    stock: 19,
    couleurs: [{ nom: 'Rose', code: '#FF007F' }],
    images: ['https://res.cloudinary.com/your-cloud-name/image/upload/v1/obb-store/parfum-rose.jpg'],
    imagePrincipale: 'https://res.cloudinary.com/your-cloud-name/image/upload/v1/obb-store/parfum-rose.jpg',
    gallery: ['https://res.cloudinary.com/your-cloud-name/image/upload/v1/obb-store/parfum-rose.jpg'],
    variants: { label: 'Volume', options: ['50ml', '100ml', '200ml'] },
    note: 4.8,
    nombreAvis: 145,
    vendu: 98,
    tags: ['parfum', 'rose', 'floral'],
    featured: true,
    isPopular: true,
    isNewArrival: false,
    isActive: true
  }
];

const seedProducts = async () => {
  try {
    await mongoose.connect(process.env.MONGO_URI);
    console.log('MongoDB connecté');

    // Clear existing products
    await Product.deleteMany();
    console.log('Produits existants supprimés');

    // Insert products
    await Product.insertMany(products);
    console.log('Produits insérés avec succès');

    process.exit(0);
  } catch (error) {
    console.error('Erreur:', error);
    process.exit(1);
  }
};

seedProducts();
